# Generated by Django 5.1.2 on 2025-05-01 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since_date', models.DateField(blank=True, null=True)),
                ('group', models.CharField(choices=[('familia', 'Familia'), ('amigos', 'Amigos'), ('trabajo', 'Trabajo')], default='amigos', max_length=50)),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_rel', to='network.person')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_rel', to='network.person')),
            ],
            options={
                'unique_together': {('from_person', 'to_person')},
            },
        ),
        migrations.AddField(
            model_name='person',
            name='acquaintances',
            field=models.ManyToManyField(related_name='known_by', through='network.Relationship', to='network.person'),
        ),
    ]
