# Generated by Django 5.2.3 on 2026-09-08 07:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['user', '-timestamp'], name='vectorapp_i_user_id_4d085e_idx'),
        ),
    ]
