# Generated by Django 5.2.15 on 2026-09-11 01:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorapp', '0002_alter_interaction_timestamp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='interaction',
            name='user_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='memoryentry',
            name='entry_type',
            field=models.CharField(choices=[('fact', 'Hecho'), ('goal', 'Meta'), ('lesson', 'Lección'), ('learning', 'Aprendizaje'), ('pattern', 'Patrón'), ('tool_creation', 'Herramienta'), ('important', 'Importante'), ('visual_identity', 'Identidad Visual')], default='fact', max_length=20),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['session_id', '-timestamp'], name='vectorapp_i_session_0d42a1_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['user_name', '-timestamp'], name='vectorapp_i_user_na_3369b6_idx'),
        ),
    ]
