# Generated by Django 5.2.15 on 2026-09-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vectorapp', '0003_interaction_session_id_interaction_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryentry',
            name='confidence',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='memoryentry',
            name='identity_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='memoryentry',
            name='importance',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='memoryentry',
            name='project_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='memoryentry',
            name='scope',
            field=models.CharField(choices=[('GLOBAL', 'Global'), ('PERSONAL', 'Personal'), ('SESSION', 'Session'), ('PROJECT', 'Project')], db_index=True, default='GLOBAL', max_length=20),
        ),
        migrations.AddField(
            model_name='memoryentry',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='memoryentry',
            name='source',
            field=models.CharField(blank=True, default='system', max_length=50),
        ),
    ]
