# Generated by Django 5.2 on 2026-09-11
import re
from django.db import migrations, models


def reclassify_legacy_memories(apps, schema_editor):
    MemoryEntry = apps.get_model('vectorapp', 'MemoryEntry')
    for entry in MemoryEntry.objects.all():
        content = entry.content or ""
        scope_changed = False

        # Si ya está catalogado como PERSONAL con identidad, respetarlo
        if entry.scope == 'PERSONAL' and entry.identity_id:
            continue

        # 1. Detectar identidad visual
        m_vis = re.search(r'IDENTIDAD_VISUAL:\s*Fotografía de perfil registrada para\s+([A-Za-záéíóúÁÉÍÓÚñÑ]+)', content, re.IGNORECASE)
        if m_vis:
            name = m_vis.group(1).strip().lower()
            entry.identity_id = name
            entry.scope = 'PERSONAL'
            scope_changed = True

        # 2. Detectar Usuario: <Nombre>
        if not scope_changed:
            m_user = re.search(r'Usuario:\s*([A-Za-záéíóúÁÉÍÓÚñÑ0-9_-]+)', content, re.IGNORECASE)
            if m_user:
                username = m_user.group(1).strip().lower()
                if username not in ('anónimo', 'anonimo', 'none', ''):
                    entry.identity_id = username
                    entry.scope = 'PERSONAL'
                    scope_changed = True
                else:
                    entry.scope = 'LEGACY'
                    scope_changed = True

        # 3. Detectar relación con usuario autenticado
        if not scope_changed and getattr(entry, 'user_id', None):
            try:
                User = apps.get_model('auth', 'User')
                u = User.objects.filter(id=entry.user_id).first()
                if u and u.username:
                    entry.identity_id = u.username.lower()
                    entry.scope = 'PERSONAL'
                    scope_changed = True
            except Exception:
                pass

        # 4. Si contiene patrones de interacción, respuestas o preferencias sin identidad resuelta -> LEGACY
        if not scope_changed:
            legacy_indicators = [
                'TEMAS:', 'RESPUESTA_EXITOSA:', 'PATRONES_', 'RELEVANCIA_',
                'Mensaje:', 'Respuesta:', 'PREFERENCIA', 'IDENTIDAD',
                'preferencia', 'mi contraseña', 'mi password', 'mi editor favorito'
            ]
            if any(ind in content for ind in legacy_indicators):
                entry.scope = 'LEGACY'
                scope_changed = True

        if scope_changed:
            entry.save(update_fields=['scope', 'identity_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('vectorapp', '0004_memoryentry_confidence_memoryentry_identity_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoryentry',
            name='scope',
            field=models.CharField(
                choices=[
                    ('GLOBAL', 'Global'),
                    ('PERSONAL', 'Personal'),
                    ('SESSION', 'Session'),
                    ('PROJECT', 'Project'),
                    ('LEGACY', 'Legacy')
                ],
                db_index=True,
                default='GLOBAL',
                max_length=20
            ),
        ),
        migrations.RunPython(reclassify_legacy_memories, reverse_code=migrations.RunPython.noop),
    ]
